In [1]:
import numpy as np

In [ ]:
arr=np.array([1,2,3])
print(arr)
arr.ndim

[1 2 3]


1

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
print(np.__version__)

1.26.4


In [ ]:
arrray1=np.array(45)
print(arrray1)

45


In [ ]:
print(type(array1))

<class 'numpy.ndarray'>


In [ ]:
zd=np.array(5) #zero dimensional
od=np.array([12,10])  #one dimensional
td=np.array([[5,3,4]]) #two dimensional
thd=np.array([[[1,2,]],[[3,4]]]) #three dimensional

In [ ]:
print(zd.ndim)  #ndim is used to find dimensional type
print(od.ndim)
print(td.ndim)
print(thd.ndim)

0
1
2
3


In [ ]:
print(zd.shape)
print(od.shape)
print(td.shape)
print(thd.shape)

()
(2,)
(1, 3)
(2, 1, 2)


In [ ]:
#3d array
threed=np.array([[[1,2],[3,4]],  [[5,6],[7,8]]])
print(threed)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
threed.ndim

3

In [ ]:
threed.shape

(2, 2, 2)

In [ ]:
three=np.array([[[1,2],[3,4]],  [[5,6],[7,8]],   [[9,10],[11,12]]])
three.ndim

3

In [ ]:
three.shape

(3, 2, 2)

In [ ]:
#create a 5dimensional
a=np.array([1,2,3,4,5],ndmin=5)
print(a)

[[[[[1 2 3 4 5]]]]]


In [ ]:
#indexing access
shifan=np.array([1,2,3,4,5])
print(shifan[1])
print(shifan[1]+shifan[2])
print(shifan[1]*shifan[2])
print(shifan[1]*shifan[4])

2
5
6
10


In [ ]:
me=np.array((1+2j,9+6j))
print(me)

[1.+2.j 9.+6.j]


In [ ]:
#convert to complex
complex=np.array([1,2,3,4],dtype="complex")
print(complex)
print(complex.dtype)


[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex128


In [ ]:
complex.imag  #imaginary added numbers

array([0., 0., 0., 0.])

In [ ]:
complex.real

array([1., 2., 3., 4.])

In [ ]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
y=np.zeros((10))#add a metrix with 4 raws and 3 colums
print(y)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#convert it to 3 dimensional
y=np.zeros((2,3,4))
print(y)


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [5]:
o = np.ones(5)
print(o)

[1. 1. 1. 1. 1.]


In [3]:
x= np.full((3,3),5)
x

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
d1=np.array([2,3,5,7])
print(d1)
print(type(d1))
print(d1.dtype)
d1.shape

[2 3 5 7]
<class 'numpy.ndarray'>
int32


(4,)

In [ ]:
d2=np.array([[1,3,5],[7,6,8]])
print(d2)
print(d2.shape)
print(d2.ndim)
print(type(d2))
print(d2.dtype)

[[1 3 5]
 [7 6 8]]
(2, 3)
2
<class 'numpy.ndarray'>
int32


In [ ]:
d3=np.array([[[1,2,3],[4,5,6]],  [[7,8,9],[10,11,12]]])
print(d3)
print(d3.shape)
print(type(d3)) #datatypes
print(d3.ndim)  #calculate dimensions
print(d3.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
<class 'numpy.ndarray'>
3
int32


In [ ]:
x=np.ones(6)
print(x)

[1. 1. 1. 1. 1. 1.]


In [ ]:
a=np.array([1,2,3,4],dtype="bool")
print(a)

[ True  True  True  True]


In [ ]:
import numpy as np
hy=np.arange(2,21,2)
print(hy)

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
zz=np.arange(1,2,0.1)
print(zz)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


In [ ]:
k=np.arange(1,19,1).reshape(2,3,3)
print(k)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [ ]:
e=np.arange(1,9,1).reshape(2,2,2)
print(e)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
p=np.arange(1,10,1).reshape(3,3)
print(p)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(p[0])

[1 2 3]


In [ ]:
print(p[0:2,1:2])

[[2]
 [5]]


In [ ]:
print(p[1,1])

5


In [ ]:
print(p[0,1],p[1,1])

2 5


In [ ]:
print(p[0,0:2])
print(p[1,0:2])


[1 2]
[4 5]


In [ ]:
import numpy as np
xz=np.zeros(25)
k=xz.reshape(5,5)
print(k)
k[0,:]=1
k[4,:]=1
k[:,0]=1
k[:,4]=1
print(k)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
shifan=np.ones(25)
shifan=shifan.reshape(5,5)
print(shifan)
print("        ")
shifan[0,:]=0
shifan[4,:]=0
shifan[:,0]=0
shifan[:,4]=0
print(shifan)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
        
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
print("checkboard patterns")
abc=np.zeros((8,8),dtype=int)
abc[1::2,::2]=1
abc[::2,1::2]=1
print(abc)

checkboard patterns
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
xx=np.zeros(64)
xx=xx.reshape(8,8)
print(xx)
print("\n")
xx[1::2, ::2]=1
xx[::2,1::2]=1
print(xx)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
w=np.zeros(24)
w=w.reshape(4,6)
print(w)
print("\n")
w[0::2,2:4]=1
w[1::2,0:2]=1
w[1::2,4:]=1
print(w)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


[[0. 0. 1. 1. 0. 0.]
 [1. 1. 0. 0. 1. 1.]
 [0. 0. 1. 1. 0. 0.]
 [1. 1. 0. 0. 1. 1.]]


In [ ]:
#converting data types
arr=np.array([1.4,3.9,5.3,7.4])
new=arr.astype("int")
print(new)

[1 3 5 7]


In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4,5]) #copy
x=a.copy()
a[3]=10
print(a)
print(x)

[ 1  2  3 10  5]
[1 2 3 4 5]


In [ ]:
arr5=np.array([1,2,3,4,5,6]) #view
y=arr5.view()
arr5[0]=7
print(arr5)
print(y)

[7 2 3 4 5 6]
[7 2 3 4 5 6]


In [ ]:
print(x.base)
print(y.base)

None
[7 2 3 4 5 6]


In [ ]:
arr6=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ar=arr6.reshape(2,2,-1)
print(arr6)
print(ar)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
arr6=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ar=arr6.reshape(2,2,-1)
print(arr6)
print(ar)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#flattening the arrays,convert a higher dimension into 1 dimension
arr7=np.array([[[1,2],[3,4]],  [[5,6],[7,8]]])
v=arr7.reshape(-1)
print(v)

[1 2 3 4 5 6 7 8]


In [ ]:
#array traversing using for loop
arr=np.array([1,2,3,4,5,6,7,8,9,10])
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
a=np.full(100,3)
print(a)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
for i in a:
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
arr3d=np.array([[[1,2,3],[4,5,6]],  [[7,8,9],[10,11,12]]])
for i in arr3d:
    for j in i:
        for x in j:
            print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
#iterate elements using nditer
arr3d=np.array([[[1,2,3],[4,5,6]],  [[7,8,9],[10,11,12]]])
for x in np.nditer(arr3d):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
arr8=np.array([1,2,3])
for x in np.nditer(arr8, flags=['buffered'], op_dtypes=['S']): #change data types if you want
   print(x)              #fixed memmory location   #converting to a datatype

b'1'
b'2'
b'3'


In [ ]:
arr12=np.array([1,2,3,6,7,8,4,5,9])
for x in np.nditer(arr12,flags=["buffered"], op_dtypes=["S"]):
    print(x)

b'1'
b'2'
b'3'
b'6'
b'7'
b'8'
b'4'
b'5'
b'9'


In [ ]:
tda=np.array([[1,2,3],[4,5,6]])
tda=tda.reshape(-1)
for x in np.nditer(tda[: :2]):
    print(x)


1
3
5


In [ ]:
#iterate with index number
arr6=np.array([1,2,3])
for i,x in np.ndenumerate(arr6):
    print(i,x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
#in 2d array
arr11=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i,j in np.ndenumerate(arr11):
    print(i,j)


(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


# numpy joining array

In [ ]:
#concatenate
array1=np.array([1,2,3])
array2=np.array([4,5,6])
newarray=np.concatenate((array1,array2))
print(newarray)

[1 2 3 4 5 6]


In [ ]:
zz=np.array([5,4,3,2,1])
xx=np.array([1,2,3,4,5])
new=np.concatenate((zz,xx))
print(new)

[5 4 3 2 1 1 2 3 4 5]


In [ ]:
#concatenate in two d
m=np.array([[7,8,9],[10,11,12]])
n=np.array([[1,2,3],[4,5,6]])
mn= np.concatenate((m,n),axis=0) #raw wise adding
print(mn)

[[ 7  8  9]
 [10 11 12]
 [ 1  2  3]
 [ 4  5  6]]


In [ ]:
m=np.array([[7,8,9],[10,11,12]])
n=np.array([[1,2,3],[4,5,6]])
mn= np.concatenate((m,n),axis=1) #column wise adding
print(mn)

[[ 7  8  9  1  2  3]
 [10 11 12  4  5  6]]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[6,5,3]])
new_arr=np.concatenate((a,b),axis=0)
print(new_arr)
print(new_arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [6 5 3]]
(4, 3)


In [ ]:
#concatinate in 3dimension
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[6,5,3]]])
b=np.array([[[7,8,9],[6,5,3]],[[1,2,3],[4,5,6]]])
new_arr=np.concatenate((a,b),axis=0)
print(new_arr)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [6 5 3]]

 [[7 8 9]
  [6 5 3]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[6,5,3]]])
b=np.array([[[7,8,9],[6,5,3]],[[1,2,3],[4,5,6]]])
new_arr=np.concatenate((a,b),axis=1)
print(new_arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [6 5 3]]

 [[7 8 9]
  [6 5 3]
  [1 2 3]
  [4 5 6]]]


In [ ]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[6,5,3]]])
b=np.array([[[7,8,9],[6,5,3]],[[1,2,3],[4,5,6]]])
new_arr=np.concatenate((a,b),axis=2)
print(new_arr)

[[[1 2 3 7 8 9]
  [4 5 6 6 5 3]]

 [[7 8 9 1 2 3]
  [6 5 3 4 5 6]]]


# stacking

In [ ]:
b=np.array([1,2,3])
c=np.array([1,2,4])
a=np.stack((b,c))
print(a)

[[1 2 3]
 [1 2 4]]


In [ ]:
b=np.array([1,2,3])
c=np.array([1,2,4])
a=np.stack((b,c),axis=1)  #colum wise stacking
print(a)

[[1 1]
 [2 2]
 [3 4]]


In [ ]:
#stacking in 2dimensions
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
x=np.stack((a,b),axis=0)
print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
x=np.stack((a,b),axis=1)
print(x)

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
x=np.stack((a,b),axis=2)
print(x)

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [ ]:
#stack in 3dimension
td1=np.array([[[1,2],[3,4]]  , [[5,6],[7,8]]])
td2=np.array([[[11,12],[13,14]],   [[15,16],[17,18]]])
m=np.stack((td1,td2),axis=0)
print(m)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[11 12]
   [13 14]]

  [[15 16]
   [17 18]]]]


In [ ]:
td1=np.array([[[1,2],[3,4]]  , [[5,6],[7,8]]])
td2=np.array([[[11,12],[13,14]],   [[15,16],[17,18]]])
m=np.stack((td1,td2),axis=1)
print(m)

[[[[ 1  2]
   [ 3  4]]

  [[11 12]
   [13 14]]]


 [[[ 5  6]
   [ 7  8]]

  [[15 16]
   [17 18]]]]


In [ ]:
td1=np.array([[[1,2],[3,4]]  , [[5,6],[7,8]]])
td2=np.array([[[11,12],[13,14]],   [[15,16],[17,18]]])
m=np.stack((td1,td2),axis=2)
print(m)

[[[[ 1  2]
   [11 12]]

  [[ 3  4]
   [13 14]]]


 [[[ 5  6]
   [15 16]]

  [[ 7  8]
   [17 18]]]]


In [ ]:
td1=np.array([[[1,2],[3,4]]  , [[5,6],[7,8]]])
td2=np.array([[[11,12],[13,14]],   [[15,16],[17,18]]])
m=np.stack((td1,td2),axis=3)
print(m)

[[[[ 1 11]
   [ 2 12]]

  [[ 3 13]
   [ 4 14]]]


 [[[ 5 15]
   [ 6 16]]

  [[ 7 17]
   [ 8 18]]]]


In [ ]:
#stacking with dstack(all dimensions will be same)
x=np.array([[1,2,3],[7,5,3]])
y=np.array([[4,5,6],[7,8,9]])
z=np.dstack((x,y))   #colum wise stacking
print(z)

[[[1 4]
  [2 5]
  [3 6]]

 [[7 7]
  [5 8]
  [3 9]]]


In [ ]:
#staking using hstack
x=np.array([[1,2,3],[3,4,5]])
y=np.array([[4,5,6],[4,5,6]])
z=np.hstack((x,y))
print(z)       #horizondal stacking

[[1 2 3 4 5 6]
 [3 4 5 4 5 6]]


In [ ]:
#stacking using vstack
x=np.array([[1,2,3],[3,4,5]])
y=np.array([[4,5,6],[4,5,6]])
z=np.vstack((x,y))
print(z)     #vertical stacking

[[1 2 3]
 [3 4 5]
 [4 5 6]
 [4 5 6]]


In [ ]:
#dstack
x=np.arange(1,25).reshape(2,3,4)
print(x)
y=np.dstack(x)
print(y)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[[ 1 13]
  [ 2 14]
  [ 3 15]
  [ 4 16]]

 [[ 5 17]
  [ 6 18]
  [ 7 19]
  [ 8 20]]

 [[ 9 21]
  [10 22]
  [11 23]
  [12 24]]]
