In [ ]:
import numpy as np

In [ ]:
#add array elements
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[1,2,3]])
add=np.add(arr1,arr2)
print(add)

[[ 8 10 12]
 [ 5  7  9]]


In [ ]:
#substract array elements
arr=np.array([6,7,8,9,10])
ar=np.array([1,2,3,4,5])
new=np.subtract(arr,ar)
print(new)

[5 5 5 5 5]


In [ ]:
#multiply array elements
arr=np.array([6,7,8,9,10])
ar=np.array([1,2,3,4,5])
new_=np.multiply(arr,ar)
print(new_)

[ 6 14 24 36 50]


In [ ]:
d=np.array([2,3,4,5])
f=np.array([1,2,3,4])
div=np.divide(d,f)
print(div)

[2.         1.5        1.33333333 1.25      ]


In [ ]:
td1=np.array([[1,2,3,4,5],[5,6,7,8,9]])
trans=np.transpose(td1)
print(trans)

[[1 5]
 [2 6]
 [3 7]
 [4 8]
 [5 9]]


In [ ]:
all=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,7,9],[2,3,4]])
add=np.add(all,b)
print(add,"\n")
sub=np.subtract(all,b)
print(sub,"\n")
multy=np.multiply(all,b)
print(multy,"\n")
div=np.divide(all,b)
print(div,"\n")
trans=np.transpose(all)
print(trans,"\n")


[[ 2  9 12]
 [ 6  8 10]] 

[[ 0 -5 -6]
 [ 2  2  2]] 

[[ 1 14 27]
 [ 8 15 24]] 

[[1.         0.28571429 0.33333333]
 [2.         1.66666667 1.5       ]] 

[[1 4]
 [2 5]
 [3 6]] 



In [ ]:
x=np.array([[1,2],[4,5]])
y=np.array([[7,8],[10,11]])
print(x)
print(y)

print(np.matmul(x,y))

[[1 2]
 [4 5]]
[[ 7  8]
 [10 11]]
[[27 30]
 [78 87]]


In [ ]:
a=np.ones(36)
a=a.reshape(6,6)
print(a)
print("")
a[0,:]=0
a[5,:]=0
a[ :,0]=0
a[:,5]=0
a[2:4,2:4]=2
print(a)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 2. 2. 1. 0.]
 [0. 1. 2. 2. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
#another method
a=np.zeros(36)
a=a.reshape(6,6)
print(a)
print("")
a[1:5 ,1:5]=1
a[2:4 , 2:4]=2

print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 2. 2. 1. 0.]
 [0. 1. 2. 2. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
p=np.zeros(30)
p=p.reshape(5,6)
print(p,"\n")
p[0::4 , 0::5]=1
p[1::2 , 1::3]=1
p[2:3 , 2:4]=1
print(p)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[1. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5,6])
new_arr=np.split(arr,3)
print(new_arr)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# array_split an array
arr=np.array([1,2,3,4,5,6])
new=np.array_split(arr,3)
print(new)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=np.array_split(a,2)
print(b)
print(b[1])

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]
[ 7  8  9 10 11 12]


In [ ]:
x=np.arange(1,13).reshape(6,2)
print(x)
b=np.array_split(x,2)
print(b)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[ 7,  8],
       [ 9, 10],
       [11, 12]])]


In [ ]:
arr=np.arange(1,19).reshape(6,3)
print(arr)
new=np.array_split(arr,1)
print(new)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])]


In [ ]:
x=np.arange(1,19).reshape(6,3)
print(x)
y=np.hsplit(x,3) #colum wise splitting[[ 1  2  3]
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
x=np.arange(1,19).reshape(6,3)
print(x)
y=np.vsplit(x,3)
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
#dsplit
a=np.arange(1,25).reshape(2,3,4)
print(a)
new=np.dsplit(a,2)
print(new)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[array([[[ 1,  2],
        [ 5,  6],
        [ 9, 10]],

       [[13, 14],
        [17, 18],
        [21, 22]]]), array([[[ 3,  4],
        [ 7,  8],
        [11, 12]],

       [[15, 16],
        [19, 20],
        [23, 24]]])]
