In [ ]:
import numpy as np

In [ ]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
z=np.add(x,y)
print(z)

[ 6  8 10 12]


In [ ]:
x=[1,2,3,4]
y=[5,6,7,8]
z=np.add(x,y)
print(z)
print(type(np.add))

[ 6  8 10 12]
<class 'numpy.ufunc'>


In [ ]:
a=[[[1,2],[3,4]],  [[5,6],[7,8]]]
b=[[[1,2],[3,4]],   [[5,6],[7,8]]]
c=np.add(a,b)
print(c)

[[[ 2  4]
  [ 6  8]]

 [[10 12]
  [14 16]]]


# creating univesal functions

In [ ]:
#create a numpy function for adding two numbers
import numpy as np
def myadd(a,b):
    return a+b
myadd=np.frompyfunc(myadd,2,1)
print(myadd([1,2,3,4],[5,6,7,8]))

[6 8 10 12]


In [ ]:
#create numpy function to multiply two arrays
def mymulty(a,b):
    return a*b
mymulty=np.frompyfunc(mymulty,2,1)
print(mymulty([1,2,3],[4,5,6]))
print(type(mymulty))

[4 10 18]
<class 'numpy.ufunc'>


In [ ]:
#adding 3 single dimension arrays
def myfun(a,b,c):
    return a+b+c
myfun=np.frompyfunc(myfun,3,1)
print(myfun([1,2,3],[4,5,6],[7,8,9]))

[12 15 18]


In [ ]:
#substractt
def mysub(a,b):
    return a-b
mysub=np.frompyfunc(mysub,2,1)
print(mysub([7,8,9],[4,5,6]))

[3 3 3]


In [ ]:
#write a numpy program that create a custom universal function
#that adds 10 to every element in a numpy array.
#use this universal fuction on a 1dimension array of integers
def addadd(n):
  return n+10
addadd=np.frompyfunc(addadd,1,1)
print(addadd([1,2,3]))

[11 12 13]


In [ ]:
#write a numpy program that uses the np.sqrt universal function
#to compute the squareroot of each elements in a 2dimensional numpy array
def mysqrt(a):
    return np.sqrt(a)
mysqrt=np.frompyfunc(mysqrt,1,1)
print(mysqrt([[16,25,81],[10,36,40]]))

[[4.0 5.0 9.0]
 [3.1622776601683795 6.0 6.324555320336759]]


In [ ]:
def sqrt(a):
    return a**0.5
sqrt=np.frompyfunc(sqrt,1,1)
print(sqrt([[25,10,20],[9,16,7]]))

[[5.0 3.1622776601683795 4.47213595499958]
 [3.0 4.0 2.6457513110645907]]


In [ ]:
#write a numpy program that creates a 2d numpy array and a 1d array.
#use the np.add universal function to add the 1 dimensional array to each row of the 2d array
def adds(a,b):
    return np.add(a,b)
adds=np.frompyfunc(adds,2,1)
print(adds([[1,2,3],[4,5,6]],  [1,2,3]))

[[2 4 6]
 [5 7 9]]


In [ ]:
def adds(a,b):
    return a+b
adds=np.frompyfunc(adds,2,1)
print(adds([[1,2,3],[4,5,6]],  [1,2,3]))

[[2 4 6]
 [5 7 9]]


In [ ]:
#write a numpy program that uses np.multiply universal function
#to perform element wise multiplicatin of two two dimensional arrays of the same shape
def multys(a,b):
    return np.multiply(a,b)
multys=np.frompyfunc(multys,2,1)
print(multys([[1,2,3],[4,5,6]],  [[2,3,4],[5,6,7]]))

[[2 6 12]
 [20 30 42]]


## check if  a function is ufunc

#Check the type of a function to check if it is a ufunc or not.

In [ ]:
if type(np.add) == np.ufunc:
   print("add is ufunction")
else:
   print("not a ufunction")


add is ufunction


## some ufunctions

#The add() function sums the content of two arrays, and return the results in a new array.

In [ ]:
from numpy import random
a=random.randint(1,10,5)
b=np.arange(1,6)
c=np.add(a,b)
print(a,"\n",b)
print(c)

[3 8 5 6 3] 
 [1 2 3 4 5]
[ 4 10  8 10  8]


In [ ]:
#substract
a=np.arange(1,10).reshape(3,3)
b=random.randint(1,10,size=(3,3))
c=np.subtract(a,b)
print(a,"\n","\n",b)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 
 [[9 6 1]
 [2 5 1]
 [6 3 5]]
[[-8 -4  2]
 [ 2  0  5]
 [ 1  5  4]]


In [ ]:
#multiply
a=np.arange(1,10).reshape(3,3)
b=random.randint(1,10,size=(3,3))
c=np.multiply(a,b)
print(a,"\n","\n",b)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 
 [[3 4 6]
 [1 2 5]
 [9 5 9]]
[[ 3  8 18]
 [ 4 10 30]
 [63 40 81]]


In [ ]:
#power
a=np.arange(1,10).reshape(3,3)
b=random.randint(1,10,size=(3,3))
c=np.power(a,b)
print(a,"\n","\n",b)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 
 [[6 4 6]
 [2 3 5]
 [7 1 6]]
[[     1     16    729]
 [    16    125   7776]
 [823543      8 531441]]


In [ ]:
#remainder
arr1=np.array([5,6,7])
arr2=np.array([3,4,5])
x=np.remainder(arr1,arr2)
print(x)

[2 2 2]


In [ ]:
#mod
arr1=np.array([5,6,7])
arr2=np.array([3,4,5])
x=np.mod(arr1,arr2)
print(x)

[2 2 2]


In [ ]:
#quotient and remainder
arr1=np.array([5,6,7])
arr2=np.array([3,4,5])
x=np.divmod(arr1,arr2)
print(x)

(array([1, 1, 1]), array([2, 2, 2]))


In [ ]:
#write a numpy program that create a custom universal function that computes
#x^2+2*+1 for each element in a numpy arrray
def newfun(a):
    return a**2 +2*a+1
newfun=np.frompyfunc(newfun,1,1)
print(newfun([4,5,6]))

[25 36 49]


In [ ]:
#absolute value
arr1=np.array([4,-3,2,-1])
new=np.absolute(arr1)
print(new)

[4 3 2 1]


# rounding methods in numpy

## trunc and fix

In [ ]:
import numpy as np
arr=np.trunc([3.1233,-2.5465,2.5445])
print(arr)

[ 3. -2.  2.]


In [ ]:
import numpy as np
arr=np.fix([3.1233,-2.5465,2.5445])
print(arr)

[ 3. -2.  2.]


## around

In [ ]:
a=np.array([2.6333,5.2878,3.7222])
b=np.around(a)
print(b)

[3. 5. 4.]


In [ ]:
x=random.rand(3)
print(x)
y=np.around(x)
print(y)

[0.1231267  0.18541631 0.61714201]
[0. 0. 1.]


In [ ]:
s=np.around(3.6999)
print(s)

4.0


## floor

In [ ]:
#near lowest integer
ar=np.floor([-3.112211, 4.7777])
print(ar)

[-4.  4.]


## ceil

In [ ]:
#near highest integers
import numpy as np
arr=np.ceil([3.23434,-4.7676])
print(arr)

[ 4. -4.]


# summation over an array

In [ ]:
arr1=np.array([1,4,6,8])
arr2=np.array([1,2,3,4])
a=np.sum([arr1,arr2])
print(a)

29


In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([5,6,10])
a=np.sum((arr1,arr2))
print(a)

27


In [ ]:
#summation with axis 0  - colum wise summation
arr1=np.array([1,2,3,4,5])
arr2=np.arange(6,11)
sum=np.sum((arr1,arr2),axis=0)
print(sum)

[ 7  9 11 13 15]


In [ ]:
# summation with axis 1  -  row wise summation
x=np.array([1,2,3])
y=np.array([5,6,7])
z=np.sum((x,y),axis=1)
print(z)

[ 6 18]


## cumalative sum

In [ ]:
from numpy import random
arr1=np.random.randint(1,10,5)
c=np.cumsum(arr1)
print(arr1)
print(c)

[3 5 8 7 1]
[ 3  8 16 23 24]


In [ ]:
#cumalative sum in 2dimensions
arr=np.array([[1,2,3],[4,5,6]])
c=np.cumsum(arr)
print(arr)
print(c)

[[1 2 3]
 [4 5 6]]
[ 1  3  6 10 15 21]


## prod

In [ ]:
x=np.array([3,4,5])
print(np.prod(x))

60


In [ ]:
x=np.array([3,4,5,2,3])
y=np.prod(x)
print(y)

360


In [ ]:
#product within two arrays
arr1=np.array([3,2,4])
arr2=np.array([1,2,3])
arr3=np.prod((arr1,arr2))
print(arr3)

144


In [ ]:
#product over axis =0
arr1=np.array([3,2,4])
arr2=np.array([1,2,3])
arr3=np.prod([arr1,arr2],axis=0)   #colum wise productin
print(arr3)

[ 3  4 12]


In [ ]:
arr1=np.array([3,2,4])
arr2=np.array([1,2,3])
arr3=np.prod([arr1,arr2],axis=1)  #raw wise producting
print(arr3)

[24  6]


## cumulative product

In [ ]:
x=np.array([5,6,7,8])
y=np.cumprod(x)
print(y)

[   5   30  210 1680]


# difference

In [ ]:
a=np.array([10,12,15,18])
b=np.diff(a)
print(b)

[2 3 3]


In [ ]:
x=np.array([5,7,10,15])
y=np.diff(x)
print(y)

[2 3 5]


In [ ]:
arr=np.array([10,15,25,5])
a=np.diff(arr,n=2)
print(a)      #5,10,-20
              #5,-30

[  5 -30]


# log

In [ ]:
a=np.array([2,5,15,9])
b=np.log(a)
print(b)

[0.69314718 1.60943791 2.7080502  2.19722458]


# log2

In [ ]:
a=np.array([2,5,15,9])
b=np.log2(a)
print(b)

[1.         2.32192809 3.9068906  3.169925  ]


In [ ]:
x=np.arange(8).reshape(2,4)
y=np.log2(x)
print(y)

[[      -inf 0.         1.         1.5849625 ]
 [2.         2.32192809 2.5849625  2.80735492]]


<ipython-input-50-f1b866f898c6>:2: RuntimeWarning: divide by zero encountered in log2
  y=np.log2(x)


# lowest comman multiple

In [ ]:
a=6
b=4
x=np.lcm(a,b)
print(x)

12


## Finding LCM in Arrays

In [ ]:
import numpy as np
arr = np.array([3, 6, 9])
x = np.lcm.reduce(arr)
print(x)

18


# greatest comman denominator

In [ ]:
import numpy as np
arr = np.array([20,8,6])
x = np.gcd.reduce(arr)
print(x)

2


# Finding GCD in Arrays

In [ ]:
import numpy as np
arr = np.array([20, 8, 32, 36, 16])
x = np.gcd.reduce(arr)
print(x)

4


# Trigonometric Functions

## sin

#NumPy provides the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, cos and tan values.

In [ ]:
#radian values of degrees
#(90degree=pi/2,   60=pi/3,   45=pi/4,  30=pi/6,  0=0,  180=pi,   360=pipi)

In [ ]:
import numpy as np
x=np.sin(np.pi/2)
print(x)

1.0


In [ ]:
arr=np.sin([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
print(arr)

[1.         0.8660254  0.70710678 0.58778525]


## cos

In [ ]:
x=np.cos(np.pi/2)
print(x)

6.123233995736766e-17


In [ ]:
arr=np.cos([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
print(arr)

[6.12323400e-17 5.00000000e-01 7.07106781e-01 8.09016994e-01]


## tan

In [ ]:
x=np.tan(np.pi/2)
print(x)

1.633123935319537e+16


In [ ]:
arr=np.tan([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
print(arr)

[1.63312394e+16 1.73205081e+00 1.00000000e+00 7.26542528e-01]


## Convert Degrees Into Radians - deg2rad

In [ ]:
arr=np.array([30,90,180])
x=np.deg2rad(arr)
print(x)

[0.52359878 1.57079633 3.14159265]


In [ ]:
arr=np.array(360)
x=np.deg2rad(arr)
print(x)

6.283185307179586


In [ ]:
a=np.array(90)
print(np.deg2rad(a))

1.5707963267948966


## Radians to Degrees - rad2deg

In [ ]:
x=np.array(1.5707963267948966)
y=np.rad2deg(x)
print(y)

90.0


## Angles of Each Value in Arrays

In [ ]:
arr = np.array([1, -1, 0.1])
x = np.arcsin(arr)
print(x)

[ 1.57079633 -1.57079633  0.10016742]


## hypotenes

In [ ]:
base = 3
perp = 4
x = np.hypot(base, perp)
print(x)


5.0


In [ ]:
base = 5
perp = 6
x = np.hypot(base, perp)
print(x)


7.810249675906654
