# Create Sets in NumPy

In [ ]:
import numpy as np
arr=np.array([1,1,1,2,3,4,5,5,6,7])
x=np.unique(arr)
print(x)
print(type(x))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [ ]:
arr=np.array([9,1,1,2,3,4,5,5,6,7])
x=np.unique(arr)
print(x)

[1 2 3 4 5 6 7 9]


## Finding Union

In [ ]:
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
newarr=np.union1d(arr1,arr2)
print(newarr)

[1 2 3 4 5 6]


In [ ]:
arr1=np.array([[1,2,],[3,4]])
arr2=np.array([[3,4],[4,6]])
newarr=np.union1d(arr1,arr2)
print(newarr)

[1 2 3 4 6]


## Finding Intersection

In [ ]:
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
newarr=np.intersect1d(arr1,arr2,assume_unique=True)
print(newarr)

[3 4]


In [ ]:
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
newarr=np.intersect1d(arr1,arr2)
print(newarr)

[3 4]


## Finding Difference

In [ ]:
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
newarr=np.setdiff1d(arr1,arr2,assume_unique=True)
print(newarr)

[1 2]


In [ ]:
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
newarr=np.setdiff1d(arr1,arr2)
print(newarr)

[1 2]


## Finding Symmetric Difference

In [ ]:
#To find only the values that are NOT present in BOTH sets, use the setxor1d() method.
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
newarr=np.setxor1d(arr1,arr2)
print(newarr)

[1 2 5 6]


In [ ]:
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
newarr=np.setxor1d(arr1,arr2,assume_unique=True)
print(newarr)

[1 2 5 6]


# Input Output Functions

In [ ]:
import numpy as np
#create a numpy array
arr=np.array([[1,2,3],[4,5,6]])
#save the array to a file
np.save('file.npy',arr)

In [ ]:
#load the saved array
loaded_array=np.load('file.npy')
print(loaded_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
# save an array as txt file
x=np.array([[5,6,7],[7,8,9]])

#save the data as a txt file
np.savetxt('folder.txt',x)
#load the txt file
load=np.loadtxt('folder.txt')
print(load)

[[5. 6. 7.]
 [7. 8. 9.]]


# Numpy comparison Operators

In [ ]:
a=np.array([4,6,3])
b=np.array([3,4,5])
print(a>b)

[ True  True False]


In [ ]:
x=np.array([2,5,5])
y=np.array([3,4,6])
z=x<y
print(z)

[ True False  True]


In [ ]:
a=np.array([4,5,6])
b=np.array([5,5,5])
print(a==b)

[False  True False]


In [ ]:
a=np.array([4,5,6])
b=np.array([5,5,5])
print(a>=b)

[False  True  True]


In [ ]:
arr1=np.array([1,3,5])
arr2=np.array([2,3,4])
print(a<=b)

[ True  True False]


In [ ]:
a=np.array([4,5,6])
b=np.array([3,5,7])
print(a != b)

[ True False  True]


# comparison operations  using functions

In [ ]:
a=np.array([4,6,3])
b=np.array([3,4,5])
c=np.greater(a,b)
print(c)

[ True  True False]


In [ ]:
x=np.array([2,5,5])
y=np.array([3,4,6])
print(np.less(x,y))

[ True False  True]


In [ ]:
a=np.array([4,5,6])
b=np.array([5,5,5])
print(np.equal(a,b))

[False  True False]


In [ ]:
a=np.array([4,5,6])
b=np.array([5,5,5])
print(np.greater_equal(a,b))

[False  True  True]


In [ ]:
arr1=np.array([1,3,5])
arr2=np.array([2,3,4])
print(np.less_equal(arr1,arr2))

[ True  True False]


In [ ]:
a=np.array([4,5,6])
b=np.array([3,5,7])
print(np.not_equal(a,b))

[ True False  True]


# boolian operators

In [ ]:
x=np.array([True,False,True])
y=np.array([True,True,False])
print(np.logical_and(x,y))

[ True False False]


In [ ]:
# logical_or
arr=np.array([True,False,True])
arr1=np.array([False,True,False])
print(np.logical_or(arr,arr1))

[ True  True  True]


In [ ]:
#logical_not
a=np.array([True,False,True,False])
print(np.logical_not(a))

[False  True False  True]


In [ ]:
x=np.array([True,False,True,False])
y=np.logical_not(x)
print(y)

[False  True False  True]


# numpy string functions

In [ ]:
import numpy as np
a=np.array(["samsung: ","prize: "])
b=np.array(["15","150000"])
c=np.char.add(a,b)
print(c)

['samsung: 15' 'prize: 150000']


In [ ]:
a=np.array(["samsung: ","prize: "])
c=np.char.multiply(a,3)
print(c)

['samsung: samsung: samsung: ' 'prize: prize: prize: ']


In [ ]:
a=np.array(["shifan","insaf","edwimn"])
b=np.char.capitalize(a)
print(b)

['Shifan' 'Insaf' 'Edwimn']


In [ ]:
a=np.array(["shifan","insaf","edwimn"])
b=np.char.lower(a)
print(b)

['shifan' 'insaf' 'edwimn']


In [ ]:
a=np.array(["shifan","insaf","edwimn"])
b=np.char.upper(a)
print(b)

['SHIFAN' 'INSAF' 'EDWIMN']


In [ ]:
a=np.array(["shifan","insaf","edwimn"])
new=np.char.join(".",a)
print(new)

['s.h.i.f.a.n' 'i.n.s.a.f' 'e.d.w.i.m.n']


In [ ]:
a=np.array(["shifan","insaf","edwimn"])
b=np.array(["shifan","INSAF","mango"])
x=np.char.equal(a,b)
print(x)

[ True False False]


In [ ]:
x=np.array([[1,2,3],[1,2,1],[3,2,1]])
y=np.linalg.inv(x)
print(y)

[[ 0.   -0.5   0.5 ]
 [-0.25  1.   -0.25]
 [ 0.5  -0.5   0.  ]]


In [ ]:
z=np.linalg.det(x)
print(z)

-8.000000000000002


In [ ]:
import numpy as np

In [ ]:
arr=np.array(range(1,10))
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
x=np.full((5,3),9)
print(x)

[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]


In [ ]:
y=np.identity(5)
print(y)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
y=np.eye(3)
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
a=np.zeros_like(arr)
print(a)

[[0 0 0]
 [0 0 0]]


In [ ]:
print(np.ones_like(arr))

[[1 1 1]
 [1 1 1]]


In [ ]:
print(np.full_like(arr,4))


[[4 4 4]
 [4 4 4]]


In [ ]:
#start stop step
arr=np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
# linspace default step is 50
x=np.linspace(1,10)
print(x)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [ ]:
#crate an array of arbitory values
empty=np.empty((2,3))
print(empty)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


In [ ]:
E=np.empty_like(arr)
print(E)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
#create an array by repeatation
arr=np.array([1,2,3])
print(np.repeat(arr,2))

[1 1 2 2 3 3]


In [ ]:
#repeat an array by a specified number of times
x=np.array([1,2,3])
y=np.tile(x,3)
print(y)

[1 2 3 1 2 3 1 2 3]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(np.size(arr))

6


In [ ]:
print(np.info(arr))

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x5971f420eeb0
byteorder:  little
byteswap:  False
type: int64
None
